[org-remmina-remmina]

# Remminaでは無変換, 変換, カタカナひらがなキーを送信できないので対策する
muhenkan = overload(mod, f13)
henkan = overload(shift, f14)
katakanahiragana = overload(shift, f14)

# Remminaで | の送信ができない問題への対処

# 「￥」単押しは「ろ」単押し
yen = ro
# 「Shift + ￥」は「Ctrl + Shift + ろ」として送信し、受信側で | を組み立てる。
shift.yen = C-S-ro

